### PR TITLE
Use HDF5 C API

### PR DESCRIPTION
**Pull request by dmringo**
At some point I merged master into my branch to try to fix some build issues, resulting in the big diff here.  I don't think it's a big issue, if we're trying to track master to keep up with FleCSI API changes, but if it is, I can apply my changes to a better base and try this again.

This gives us good base on the HDF5 C API for MPAS mesh files, though there's still plenty of proper error handling to implement.  Which backend is used to instantiate a burton mesh is controlled by `FLECSI_SP_BURTON_BACKEND` in cmake.

At some point, we may want to move away from the `ifdef`s and maybe use a template parameter to control the backend.  I don't think it would be too hard to adapt what we have to that, but it would involve making more substantial changes to the burton mesh code than what we have now.

### CODE REVIEW

**Comment by dmringo** [comment]
I'll look into the issues with the conflicts.  Just wanted to get this up before leaving

**Comment by cmsquared** [comment]
Ideally, the backend as you've called it, should be controlled at runtime so that the user can say whether or not they have an HDF5 file or an Exodus file or whatever file.  I just merged my PR #49 that started to add X3D file support.  The runtime control of backend is a little annoying currently because some of the base `mesh_definition_t` API is specified in FleCSI and some is in FleCSI-SP.  I started down a path to allow runtime selection, but abandoned it in the above PR until some refactoring can happen.

**Comment by ipdemes** [comment]
@dmringo : it seems like your branch has conflicts with the hdf5_definition one. Could you, please, resolve the conflicts?

**Comment by dmringo** [comment]
@ipdemes I don't think I can reopen this.  If you can do that, the pull request should be updated with the new commits.

**Comment by ipdemes** [comment]
@charest : what should I do to reopen this pull request?

**Comment by charest** [comment]
Can you refactor this so that selects which mesh type to read runtime?

**Comment by ipdemes** [comment]
@charest : can you explain this more?

**Comment by dmringo** [comment]
@charest I can do that.  FWIW, we don't have any concrete plans to merge this into master yet.  The flecsi_sp:hdf5_definition branch hasn't been tracking it closely.

@ipdemes I think this is in reference to the `ifdef`s that select the mpas or exodus mesh.

**Pull request closed without merging**
